/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.stock_inventory_project;


import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import com.mycompany.stock_inventory_project.DBManagment;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


public class Product_stock_panel extends javax.swing.JPanel {
DBManagment db;
    /**
     * Creates new form Product_stock_panel
     */
    public Product_stock_panel() {
        initComponents();
        db = new DBManagment(); 
        loadCategories();
        loadBrands();
       loadProducts();
        loadProductsCB();
    }
    
    private void loadProductsCB() {
    productsCB.removeAllItems();
    String sql = "SELECT ProductID, ProductName FROM Products";

    try (Connection con = DBManagment.connect();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("ProductID");
            String name = rs.getString("ProductName");
            productsCB.addItem(new ComboItem(name, id));
        }

    } catch (Exception e) { e.printStackTrace(); }
}
    
    
private void tableProductsMouseClicked(java.awt.event.MouseEvent evt) {
    int row = tblProducts.getSelectedRow();

    
    productsCB.setSelectedItem(tblProducts.getValueAt(row, 1).toString());
    ComboItem.setSelectedItem(tblProducts.getValueAt(row, 2).toString());
    brandBox.setSelectedItem(tblProducts.getValueAt(row, 3).toString());
    barcodeTextField.setText(tblProducts.getValueAt(row, 4).toString());
}
  public void loadProducts() {
    DBManagment db = new DBManagment();
    List<Object[]> products = db.getProducts();

    DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
    model.setRowCount(0);

    for (Object[] row : products)
        model.addRow(row);
}
  private void loadCategories() {
    DBManagment db = new DBManagment();
    ComboItem.removeAllItems();

    String sql = "SELECT CategoryID, CategoryName FROM Categories";

    try (Connection con = DBManagment.connect();

         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("CategoryID");
            String name = rs.getString("CategoryName");
            ComboItem.addItem(new ComboItem(name, id));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void selectComboItem(JComboBox<ComboItem> box, String name) {
    for (int i = 0; i < box.getItemCount(); i++) {
        ComboItem item = box.getItemAt(i);
        if (item.getName().equals(name)) {
            box.setSelectedIndex(i);
            return;
        }
    }
}

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lıstButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        barcodeTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ComboItem = new javax.swing.JComboBox<>();
        brandBox = new javax.swing.JComboBox<>();
        productsCB = new javax.swing.JComboBox<>();

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Category Name", "Brand Name", "Bar Code"
            }
        ));
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("PRODUCTS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lıstButton.setText("LIST");
        lıstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lıstButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Barcode:");

        jLabel1.setText("Product Name:");

        jLabel2.setText("Category Name:");

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Brand Name:");

        ComboItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(updateButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcodeTextField)
                            .addComponent(brandBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ComboItem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productsCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(deleteButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(productsCB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(brandBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(barcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lıstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(144, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lıstButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void loadProductsToTable() {
   // Bağlantıyı başlat
    DBManagment db = new DBManagment();
    List<Object[]> products = db.getProducts(); // Ürünleri al

    DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
    model.setRowCount(0); // eski verileri temizle

    for (Object[] row : products) {
        model.addRow(row); // her satırı tabloya ekle
    }
}
   
private void loadBrands() {
    DBManagment db = new DBManagment();
    brandBox.removeAllItems();

    String sql = "SELECT BrandID, BrandName FROM Brands";

    try (Connection con = DBManagment.connect();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("BrandID");
            String name = rs.getString("BrandName");
            brandBox.addItem(new ComboItem(name, id));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}





    private void lıstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lıstButtonActionPerformed
       loadProductsToTable();
    }//GEN-LAST:event_lıstButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
   DBManagment db = new DBManagment();

String barcode = barcodeTextField.getText();

ComboItem selectedProduct = (ComboItem) productsCB.getSelectedItem();
ComboItem selectedCategory = (ComboItem) ComboItem.getSelectedItem();
ComboItem selectedBrand = (ComboItem) brandBox.getSelectedItem();

String productName = selectedProduct.getName();  // ✔ productID değil, name alıyoruz
int categoryID = selectedCategory.getId();
int brandID = selectedBrand.getId();

int newID = db.addProduct(productName, categoryID, brandID, barcode);

if (newID > 0) {
    db.createInitialStock(newID);
    JOptionPane.showMessageDialog(this, "Product saved!");
    loadProducts();
}

    
    
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    int row = tblProducts.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product!");
        return;
    }

    int id = Integer.parseInt(tblProducts.getValueAt(row, 0).toString());

    DBManagment db = new DBManagment();

    // ✔ product name ComboBox'tan alınmalı
    ComboItem selectedProduct = (ComboItem) productsCB.getSelectedItem();
    String productName = selectedProduct.getName();   // önemli

    String barcode = barcodeTextField.getText();

    ComboItem selectedCategory = (ComboItem) ComboItem.getSelectedItem();
    ComboItem selectedBrand = (ComboItem) brandBox.getSelectedItem();

    int categoryID = selectedCategory.getId();
    int brandID = selectedBrand.getId();

    // ✔ Artık DBManagment method imzasına uyuyor
    db.updateProduct(id, productName, categoryID, brandID, barcode);

    JOptionPane.showMessageDialog(this, "Product updated!");
    loadProducts();
    }//GEN-LAST:event_updateButtonActionPerformed


    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
     
         int row = tblProducts.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product!");
        return;
    }

    int id = Integer.parseInt(tblProducts.getValueAt(row, 0).toString());
System.out.println("Selected ID: " + tblProducts.getValueAt(row, 0));

    DBManagment db = new DBManagment();
    db.deleteProduct(id);

    JOptionPane.showMessageDialog(this, "Product deleted!");
    loadProducts();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
    int row = tblProducts.getSelectedRow();

String productName = tblProducts.getValueAt(row, 1).toString();
String categoryName = tblProducts.getValueAt(row, 2).toString();
String brandName = tblProducts.getValueAt(row, 3).toString();
String barcode = tblProducts.getValueAt(row, 4).toString();

// 1) Product seçimi
selectComboItem(productsCB, productName);

// 2) Category seçimi
selectComboItem(ComboItem, categoryName);

// 3) Brand seçimi
selectComboItem(brandBox, brandName);

// 4) Barcode text doldur
barcodeTextField.setText(barcode);


  
    }//GEN-LAST:event_tblProductsMouseClicked

    private void ComboItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComboItem> ComboItem;
    private javax.swing.JTextField barcodeTextField;
    private javax.swing.JComboBox<ComboItem> brandBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lıstButton;
    private javax.swing.JComboBox<ComboItem> productsCB;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable tblProducts;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
