/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.stock_inventory_project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hilal
 */
public class Transfer extends javax.swing.JPanel {
private INVENTORY mainFrame;
    /**
     * Creates new form Transfer
     */
    public Transfer(INVENTORY frame) {
           this.mainFrame = frame;
        initComponents();
        
       
     loadStores();
    loadProducts();
    loadCategories();
    loadBrands();       // 4) Markalar
    // 5) Seçilen mağazanın tablosu yüklenecek

    
    }
  public void refreshProductList() {
    productsCB.removeAllItems();

    DBManagment db = new DBManagment();
    List<ComboItem> productList = db.getAllProductsAsCombo();

    for (ComboItem item : productList) {
        productsCB.addItem(item);
    }
}


    private void loadStores() {
    storeCB.removeAllItems();

    String sql = "SELECT StoreID, StoreName FROM Stores";

    try (Connection con = DBManagment.connect();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            storeCB.addItem(
                new ComboItem(rs.getString("StoreName"), rs.getInt("StoreID"))
            );
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}



         


public void loadProducts() {
    productsCB.removeAllItems();

    String sql = "SELECT ProductID, ProductName FROM Products";

    try (Connection con = DBManagment.connect();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            productsCB.addItem(
                new ComboItem(rs.getString("ProductName"), rs.getInt("ProductID"))
            );
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

private void loadCategories() {
    categoryBox.removeAllItems();

    String sql = "SELECT CategoryID, CategoryName FROM Categories";

    try (Connection con = DBManagment.connect();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            categoryBox.addItem(new ComboItem(rs.getString("CategoryName"), rs.getInt("CategoryID")));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}


private void loadBrands() {
    brandBox.removeAllItems();

    String sql = "SELECT BrandID, BrandName FROM Brands";

    try (Connection con = DBManagment.connect();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            brandBox.addItem(new ComboItem(rs.getString("BrandName"), rs.getInt("BrandID")));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}




public void loadWarehouseTable() {

    int warehouseId = 1; // "Merkez Depo" = ID 1

    DBManagment db = new DBManagment();
    List<Object[]> rows = db.getWarehouseInventory(warehouseId);

    DefaultTableModel model = (DefaultTableModel) depoTable.getModel();
    model.setRowCount(0);

    for (Object[] row : rows) {
        model.addRow(row);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        storeCB = new javax.swing.JComboBox<>();
        productsCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        categoryBox = new javax.swing.JComboBox<>();
        brandBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        depoTable = new javax.swing.JTable();
        depoBttn = new javax.swing.JButton();
        transferBttn = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("TRANSFER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("To Store");

        jLabel4.setText("Select Product : ");

        storeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Category:");

        jLabel6.setText("Brand:");

        jLabel5.setText("Quantity : ");

        quantityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(storeCB, 0, 84, Short.MAX_VALUE)
                            .addComponent(productsCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brandBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(storeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(productsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brandBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        depoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Category", "Brand ", "Quantity"
            }
        ));
        depoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depoTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(depoTable);

        depoBttn.setText("LIST DEPO");
        depoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depoBttnActionPerformed(evt);
            }
        });

        transferBttn.setText("Transfer");
        transferBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(transferBttn)
                                .addGap(23, 23, 23))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(depoBttn)
                .addGap(180, 180, 180))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transferBttn)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(depoBttn)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void storeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeCBActionPerformed

    private void transferBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBttnActionPerformed
 
  // 1) Ürün seçimi
ComboItem selectedProduct = (ComboItem) productsCB.getSelectedItem();
if (selectedProduct == null) {
    JOptionPane.showMessageDialog(this, "Lütfen ürün seçin!");
    return;
}
int productId = selectedProduct.getId();

// 2) Miktar kontrolü
String qtyText = quantityTF.getText().trim();
if (qtyText.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Lütfen miktar girin!");
    return;
}

int quantity;
try {
    quantity = Integer.parseInt(qtyText);
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Miktar sayı olmalıdır!");
    return;
}

if (quantity <= 0) {
    JOptionPane.showMessageDialog(this, "Miktar 0'dan büyük olmalıdır!");
    return;
}

// 3) Depo ID – Merkez Depo = 1
int warehouseId = 1;

// 4) Depodan ürün düşme (store eklemesi YOK!)
DBManagment db = new DBManagment();
boolean success = db.transferToStore(productId, warehouseId, quantity);

if (success) {
    JOptionPane.showMessageDialog(this, "✔ Depodan ürün başarıyla düşüldü!");
    loadWarehouseTable(); // varsa tablo yenile
} else {
    JOptionPane.showMessageDialog(this, "❌ Yetersiz stok veya işlem hatası!");
}

   


    }//GEN-LAST:event_transferBttnActionPerformed

    private void depoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depoBttnActionPerformed
        loadWarehouseTable();
    }//GEN-LAST:event_depoBttnActionPerformed

    private void depoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoTableMouseClicked
 
        
       int row = depoTable.getSelectedRow();
    if (row == -1) return;

    // JTable'dan değerleri çekiyoruz
    String productName = depoTable.getValueAt(row, 0).toString();
    String categoryName = depoTable.getValueAt(row, 1).toString();
    String brandName = depoTable.getValueAt(row, 2).toString();
    String quantity = depoTable.getValueAt(row, 3).toString();

    // ✔ ComboBox'ta ilgili item’ı seçiyoruz
    selectComboBoxItem(productsCB, productName);
    selectComboBoxItem(categoryBox, categoryName);
    selectComboBoxItem(brandBox, brandName);

    // ✔ Quantity textfield kontrolü
    quantityTF.setText(quantity);
    }//GEN-LAST:event_depoTableMouseClicked

    private void quantityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTFActionPerformed

private void selectComboBoxItem(JComboBox<ComboItem> comboBox, String name) {
    for (int i = 0; i < comboBox.getItemCount(); i++) {
        ComboItem item = comboBox.getItemAt(i);
        if (item.getName().equalsIgnoreCase(name)) { 
            comboBox.setSelectedIndex(i);
            break;
        }
    }
}




    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComboItem> brandBox;
    private javax.swing.JComboBox<ComboItem> categoryBox;
    private javax.swing.JButton depoBttn;
    private javax.swing.JTable depoTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<ComboItem> productsCB;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JComboBox<ComboItem> storeCB;
    private javax.swing.JButton transferBttn;
    // End of variables declaration//GEN-END:variables
}
